#!/bin/bash

# Production Build Script for Kindred
# Builds production-ready bundles for iOS and Android

set -e  # Exit on any error

echo "🚀 Starting Kindred Production Build Process..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# Check if production environment file exists
if [ ! -f ".env.production" ]; then
    print_error "Production environment file (.env.production) not found!"
    print_error "Please create .env.production with your production secrets"
    exit 1
fi

# Backup current .env and use production config
if [ -f ".env" ]; then
    print_status "Backing up current .env file..."
    cp .env .env.backup
fi

print_status "Using production environment configuration..."
cp .env.production .env

# Clean everything first
print_status "Cleaning previous builds..."
bun run clean:metro
bun run clean:gradle

# Install dependencies
print_status "Installing dependencies..."
bun install

# Run validation suite
print_status "Running validation suite..."
bun run validate:quick

if [ $? -ne 0 ]; then
    print_error "Validation failed! Please fix issues before building production."
    # Restore original .env
    if [ -f ".env.backup" ]; then
        mv .env.backup .env
    fi
    exit 1
fi

# Build Android Release
print_status "Building Android Release Bundle..."
cd android
./gradlew clean
./gradlew bundleRelease

if [ $? -eq 0 ]; then
    print_success "Android Release Bundle created successfully!"
    print_status "Location: android/app/build/outputs/bundle/release/app-release.aab"
else
    print_error "Android Release build failed!"
    cd ..
    # Restore original .env
    if [ -f ".env.backup" ]; then
        mv .env.backup .env
    fi
    exit 1
fi

cd ..

# Build iOS Release (if on macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
    print_status "Building iOS Release..."
    
    # Install pods
    cd ios
    pod install --repo-update
    
    # Build iOS
    xcodebuild -workspace Kindred.xcworkspace -scheme Kindred -configuration Release -destination generic/platform=iOS archive -archivePath build/Kindred.xcarchive
    
    if [ $? -eq 0 ]; then
        print_success "iOS Release Archive created successfully!"
        print_status "Location: ios/build/Kindred.xcarchive"
    else
        print_error "iOS Release build failed!"
        cd ..
        # Restore original .env
        if [ -f ".env.backup" ]; then
            mv .env.backup .env
        fi
        exit 1
    fi
    
    cd ..
else
    print_warning "iOS build skipped (not running on macOS)"
fi

# Generate bundle analysis
print_status "Generating bundle analysis..."
bun run bundle:analyze > production-bundle-analysis.txt

# Generate build report
BUILD_TIME=$(date)
BUILD_VERSION=$(node -p "require('./package.json').version")
BUILD_NUMBER=$(grep -o 'BUILD_NUMBER=.*' .env.production | cut -d= -f2)

cat > production-build-report.md << EOF
# Production Build Report

**Build Time:** $BUILD_TIME
**App Version:** $BUILD_VERSION
**Build Number:** $BUILD_NUMBER
**Environment:** Production

## Build Artifacts

### Android
- **Release Bundle:** \`android/app/build/outputs/bundle/release/app-release.aab\`
- **APK:** \`android/app/build/outputs/apk/release/app-release.apk\`

### iOS (if built)
- **Archive:** \`ios/build/Kindred.xcarchive\`

## Bundle Analysis
See \`production-bundle-analysis.txt\` for detailed bundle size analysis.

## Validation Results
✅ TypeScript compilation passed
✅ ESLint validation passed
✅ Production build completed

## Next Steps
1. Test the production builds on physical devices
2. Submit to respective app stores
3. Set up monitoring for production environment

---
*Generated by Kindred Production Build Script*
EOF

print_success "Production build completed successfully!"
print_status "Build report: production-build-report.md"
print_status "Bundle analysis: production-bundle-analysis.txt"

# Restore original .env
if [ -f ".env.backup" ]; then
    print_status "Restoring original .env file..."
    mv .env.backup .env
else
    print_warning "No .env backup found, keeping production .env"
fi

print_success "🎉 Production build process completed!"
print_status "Ready for app store submission!"