#!/bin/bash

# Staging Build Script for Kindred
# Builds staging bundles for testing

set -e  # Exit on any error

echo "🧪 Starting Kindred Staging Build Process..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# Check if staging environment file exists
if [ ! -f ".env.staging" ]; then
    print_error "Staging environment file (.env.staging) not found!"
    print_error "Please create .env.staging with your staging configuration"
    exit 1
fi

# Backup current .env and use staging config
if [ -f ".env" ]; then
    print_status "Backing up current .env file..."
    cp .env .env.backup
fi

print_status "Using staging environment configuration..."
cp .env.staging .env

# Clean everything first
print_status "Cleaning previous builds..."
bun run clean:metro

# Install dependencies
print_status "Installing dependencies..."
bun install

# Run validation suite
print_status "Running validation suite..."
bun run validate:quick

if [ $? -ne 0 ]; then
    print_warning "Validation had issues, but continuing with staging build..."
fi

# Build Android Debug (for staging testing)
print_status "Building Android Staging Bundle..."
cd android
./gradlew clean
./gradlew bundleRelease

if [ $? -eq 0 ]; then
    print_success "Android Staging Bundle created successfully!"
    print_status "Location: android/app/build/outputs/bundle/release/app-release.aab"
else
    print_error "Android Staging build failed!"
    cd ..
    # Restore original .env
    if [ -f ".env.backup" ]; then
        mv .env.backup .env
    fi
    exit 1
fi

cd ..

# Build iOS Debug (if on macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
    print_status "Building iOS Staging..."
    
    # Install pods
    cd ios
    pod install
    
    # Build iOS Debug for testing
    xcodebuild -workspace Kindred.xcworkspace -scheme Kindred -configuration Debug -destination generic/platform=iOS -derivedDataPath build/
    
    if [ $? -eq 0 ]; then
        print_success "iOS Staging build completed successfully!"
    else
        print_warning "iOS Staging build had issues, but continuing..."
    fi
    
    cd ..
else
    print_warning "iOS build skipped (not running on macOS)"
fi

# Generate staging build report
BUILD_TIME=$(date)
BUILD_VERSION=$(node -p "require('./package.json').version")

cat > staging-build-report.md << EOF
# Staging Build Report

**Build Time:** $BUILD_TIME
**App Version:** $BUILD_VERSION-staging
**Environment:** Staging

## Build Artifacts

### Android
- **Staging Bundle:** \`android/app/build/outputs/bundle/release/app-release.aab\`

### iOS (if built)
- **Debug Build:** \`ios/build/\`

## Features Enabled
- All experimental features enabled
- Debug tools available
- Extended logging
- Development tools accessible

## Testing Notes
- This build includes all features for comprehensive testing
- Connect to staging API endpoints
- Crash reporting enabled for staging environment

---
*Generated by Kindred Staging Build Script*
EOF

print_success "Staging build completed successfully!"
print_status "Build report: staging-build-report.md"

# Restore original .env
if [ -f ".env.backup" ]; then
    print_status "Restoring original .env file..."
    mv .env.backup .env
else
    print_warning "No .env backup found, keeping staging .env"
fi

print_success "🎉 Staging build process completed!"
print_status "Ready for staging testing!"